env:
  - DMD: 2.071.0
  - DMD: 2.070.2
  - DMD: 2.069.2
commands:
  - curl -fsSL --retry 3 "http://downloads.dlang.org/releases/2.x/$DMD/dmd.$DMD.linux.tar.xz" | tar -C ~ -Jxf -
  - curl -fsSL --retry 3 http://code.dlang.org/files/dub-${DUB}-linux-x86_64.tar.gz | tar -C ~/dmd2/linux/bin64 -zxf -
  - dmd --version
  - dub --version
  - dub test

