sudo: false

language: d

d:
 - dmd-2.070.0-b1
 - dmd-2.069.2
 - dmd-2.068.2
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-0.17.0-alpha1
 - ldc-0.16.1
 - ldc-0.15.1
 - gdc-4.9.2
 - gdc-5.2.0

install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.1.6/doveralls_linux_travis"
  - chmod +x doveralls

script:
  - dub test -b unittest-cov

after_success:
  - bash <(curl -s https://codecov.io/bash)
