sudo: false
os:
 - linux
 - osx
language: d
env:
 - ARCH="x86_64"
matrix:
  include:
    - {os: linux, d: ldc-1.0.0-beta1, addons: {apt: {sources: [ubuntu-toolchain-r-test], packages: [[g++-4.8]]}}}
    - {os: linux, d: dmd-2.071.0, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd-2.070.2, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd-2.069.2, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd-2.068.2, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc-1.0.0-alpha1, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc-0.17.0, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
script:
 - LD_LIBRARY_PATH=~/ldc/bin/:$LD_LIBRARY_PATH
 - echo "$ARCH"
 - dub test --arch "$ARCH" -b unittest-cov
 - dub build -c median-filter
 - dub build -c means-of-columns
after_success:
 - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - devteam@mir.rocks

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2d7cb29fc776c5eaeef
    on_success: change
    on_failure: always
    on_start: never
