sudo: true
os:
 - linux
language: d
d:
 - ldc-1.0.0-beta1
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
script:
 - LD_LIBRARY_PATH=~/ldc/bin/:$LD_LIBRARY_PATH
 - echo "$ARCH"
 - dub test --arch "$ARCH" -b unittest-cov
 - dub build -c median-filter
 - dub build -c means-of-columns
after_success:
 - bash <(curl -s https://codecov.io/bash)
